### ISSUE TITLE
Load/Unload Filament

### ISSUE THREAD

**Issue by sziga** [bew1769/BTT-SKR-MINI-E3-V1-2-for-ender-5#1]
Hi,
Is there a way in Marlin to enable Load/Unload Filament in the Main Menu?
I have a bmg extruder clone so it is difficult to load the filement.

**Comment by bew1769** [comment]
I will look into that.  It sounds like a good idea.

**Comment by bew1769** [comment]
All done.  Thanks, ti works well for me.  You may have to change the values, I have my extruder mounted on the top.
